services:
    app1:
        build:
            context: app1
        ports:
            - "5000"
        networks:
            - "network1"
    app2:
        build:
            context: app2
        ports:
            - "5000"
        networks:
            - "network1"

    main_app:
        build:
            context: main_app
        ports:
            - "5000"
        networks:
            - "network1"

    nginx:
        image: nginx:latest
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app1
        ports:
            - "80:80"
        networks:
            - "network1"

networks:
    network1: